### PR TITLE
Add GitHub Action to build Docker image

### PR DESCRIPTION
**Pull request by wilsonianb**
Pushing to GitHub will publish the following Docker images to ghcr.io:

- branch --> `ghcr.io/coilhq/tigerbeetle:<branch>`
- tag --> `ghcr.io/coilhq/tigerbeetle:<tag>`
- `main` --> `ghcr.io/coilhq/tigerbeetle:latest`

You can see images created in my fork for reference, which worked without needing to change any repo settings:
https://github.com/wilsonianb/tigerbeetle/pkgs/container/tigerbeetle

I did get one build error when I pushed a tag of a commit that wasn't in any branches.
It succeeded when I re-ran the workflow after including the commit in `main`.

### CODE REVIEW

**Comment by jorangreef** [comment]
Thanks @wilsonianb

**Comment by ifreund** [comment]
As of 3a992bacbbc31710104f4a02b61d3a677bb0b4ce, running `zig build test` will run all the unit tests we have.

**Review by DonChangfoot — APPROVED** [review]
This is great @wilsonianb. Does this publish the image when the pull request is merged into `main`?

**Comment by wilsonianb** [comment]
> Does this publish the image when the pull request is merged into `main`?

Yes, the workflow would run as a `push` event (to `main`) resulting in the image being pushed
https://github.com/coilhq/tigerbeetle/pull/38/files#diff-3f5366f6d6df3ec1179e5efadc6f350bfa88eebf4e2da589b4d94ccb85ae5e94R52

**Comment by jorangreef** [comment]
Thanks @wilsonianb !

**Pull request merged**
